# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: maximopeoficiales
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-example-api-ts

provider:
  name: aws
  runtime: nodejs20.x
build:
  esbuild: false
plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"
