# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: maximopeoficiales
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-example-api-ts

provider:
  name: aws
  runtime: nodejs20.x

# Habilita la opción de ESBuild
build:
  esbuild:
    bundle: true        # Genera un solo archivo
    external: ["aws-sdk"] # Excluye aws-sdk para que no se incluya en el bundle

plugins:
  - serverless-offline

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"
